# Generated by Django 4.1.6 on 2023-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
